---
- block:
    - name: Check envfile presence
      stat:
        path: "{{ victoriametrics_service_envflag_file }}"
      register: envfile_state

    - name: Setup envfile
      file:
        state: touch
        path: "{{ victoriametrics_service_envflag_file }}"
        owner: root
        group: root
        mode: 0644
        access_time: preserve
      notify: Restart VictoriaMetrics service
      when: envfile_state.stat.exists is defined and not envfile_state.stat.exists
  when: victoriametrics_service_envflag_enabled | bool

- name: Copy VictoriaMetrics systemd unit file
  template:
    src: victoriametrics.service.j2
    dest: /etc/systemd/system/victoriametrics.service
    owner: root
    group: root
    mode: 0644
  register: config_template
  no_log: True

- name: daemon-reload VictoriaMetrics service
  become: true
#  notify: Restart VictoriaMetrics service
  systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
#  when: config_template is changed

- name: Ensure VictoriaMetrics service is enabled on boot
  become: true
  systemd:
    name: victoriametrics
    enabled: true
    state: started
  when: config_template is changed

- block:
  - name: Create aws credentials dir
    become: true
    file:
      path: ~/.aws
      state: directory

  - name: Create aws config file
    become: true
    copy:
      dest: ~/.aws/config
      content: |
        [default]
        region = eu-west-1
        output = json

  - name: Template credentials file
    template:
      src: creds.j2
      dest: ~/.aws/credentials

  - name: Set proxy config
    set_fact:
      _victoria_backup_proxy: "http_proxy={{ http_proxy }} https_proxy={{ http_proxy }} "
    when:
    - victoriametrics_backup_proxy_enable
    - http_proxy is defined

  - name: Configure cron
    cron:
      name: "backup victoriametrics data"
      user: root
      state: present
      hour: "{{ victoriametrics_backup_cron_hour }}"
      job: "{{ _victoria_backup_proxy | default(omit) }} /usr/local/bin/vmbackup-prod -snapshot.createURL=http://localhost:8428/snapshot/create {% if victoriametrics_backup_custom_s3_endpoint != '' %} -customS3Endpoint {{ victoriametrics_backup_custom_s3_endpoint }} {% endif %} -storageDataPath {{ victoriametrics_data_dir }} -dst {{ victoriametrics_backup_destination }}/$(date +\\%Y-\\%m-\\%d)"

  when: victoriametrics_backup_enabled | bool

- name: Delete cron if backup disabled
  cron:
    name: "backup victoriametrics data"
    user: root
    hour: "{{ victoriametrics_backup_cron_hour }}"
    state: absent
  when: not victoriametrics_backup_enabled | bool
